## Excercise 1:  
#### Create an array of 100 random elements. Calc median. 

Author: Pedro Ciancaglini

In [ ]:
# Importing required libraries
import numpy as np

In [ ]:
# Creating our random array with 100 elements
random_array = np.random.randint(100,size=100)
random_array

array([51, 98, 38, 39, 46, 26, 95, 96,  2, 72, 26, 49,  8, 21, 99, 67, 87,
       11, 76, 84, 86, 91, 92,  9, 56, 79, 24, 85,  8, 27, 75, 90, 25, 34,
       75, 61, 65, 61, 52, 41, 34,  3, 88,  3, 87, 16, 40, 57, 59, 29,  3,
        7, 80, 24, 91, 58, 36, 76, 76, 23, 14, 79, 93, 75, 48, 12, 63, 71,
       58, 99, 12, 98, 60, 42, 82, 18, 95, 72, 21, 85, 37, 16, 22,  2, 55,
       36, 66, 37,  2, 12, 30, 93, 20,  5, 73, 57, 30, 37, 51, 70])

In [ ]:
# Calculating median
median_array = np.median(random_array)
median_array

58.0

In [ ]:
# With reshape, you can create a Matrix from an Array 
reshaped_array = random_array.reshape(10,10) # 10x10 Matrix
print(reshaped_array)

[[51 98 38 39 46 26 95 96  2 72]
 [26 49  8 21 99 67 87 11 76 84]
 [86 91 92  9 56 79 24 85  8 27]
 [75 90 25 34 75 61 65 61 52 41]
 [34  3 88  3 87 16 40 57 59 29]
 [ 3  7 80 24 91 58 36 76 76 23]
 [14 79 93 75 48 12 63 71 58 99]
 [12 98 60 42 82 18 95 72 21 85]
 [37 16 22  2 55 36 66 37  2 12]
 [30 93 20  5 73 57 30 37 51 70]]


In [ ]:
##### Function to select an element from the random array ######
def selection(arr):
   
    choose = int(input("Select a vector in the array to operate> ")) 

    while choose > len(arr):                                             
        choose = int(input("It must be a vector in the array> "))
    
    return arr[choose,]                                                  

print(selection(reshaped_array))                                          

Select a vector in the array to operate> 1
[26 49  8 21 99 67 87 11 76 84]


**Exercise 2>** 
#### Creating vectorial operational functions and sum on a serie

In [ ]:
# function to make a sum in serie of the whole vector
def addition(arr):                                   
    res = 0                               
    
    for i in arr:                              
        res += i

    print("Result via loop: ", res)             
    print("Result by using native Numpy Function> ", arr.sum()) 

In [ ]:
addition(seleccion(reshaped_array)) 

Select a vector in the array to operate> 1
Result via loop:  528
Result by using native Numpy Function>  528


In [ ]:
%time 
arr = np.random.randint(1000, size=(100,100))
addition(arr)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.11 µs
Result via loop:  [47684 48972 50972 45614 45766 46420 47480 51204 49322 45182 50151 46992
 53116 50226 51151 54692 52951 54295 54703 46391 44582 47885 51654 49573
 50229 53232 48144 44692 50295 49458 48692 46484 58572 49612 51746 47506
 49641 52250 49953 49244 50752 49705 50979 43229 49056 45620 49316 46872
 49405 50103 46404 49018 50768 44889 52559 52406 52353 53775 47997 49797
 45216 54151 44387 50619 51558 47217 42128 54379 51756 45952 49479 49965
 51331 49431 51492 49377 47846 47757 46076 45542 47849 52402 43910 49585
 50193 48556 48500 52446 51318 52383 44455 49495 47866 49170 46211 53947
 51474 50081 51560 48955]
Result by using native Numpy Function>  4937746


In [ ]:
%time       # One important metric in Data Science is the quantity of time need to run an algorithm. Measuring execution time is important. 
arr.sum()

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.87 µs


4937746

### Note:

A great feature in Jupyter notebook are the magic functions, en this case, I used %time which allow us to take a quick look at how much time our cell is taking to run. 

Executing small vectors and comparing with a loop and a Numpy method is useful but while the vector or array is growing, it will take longer to analyze with loop and it will be faster with this magic function. This is when we are more convinced of the power of Numpy

###### Vector operations - Addition and Product

In [ ]:
def vector_addition(vec1,vec2):      
    res = vec1 + vec2                 
    return res                     

In [ ]:
print(vector_addition(selection(reshaped_array),selection(reshaped_array)))  # printing the sum of two different selected vectors

Select a vector in the array to operate> 1
Select a vector in the array to operate> 2
[112 140 100  30 155 146 111  96  84 111]


In [ ]:
# function for product with two vectors
def vector_prod(vec1, vec2):             
    res = np.matmul(vec1, vec2)      
    return res                       

In [ ]:
vector_prod(selection(reshaped_array),selection(reshaped_array))

Select a vector in the array to operate> 1
Select a vector in the array to operate> 2


24356

## Excercise 3> 
#### Introducing to Pandas, Data Formats, Data Frames
This file is a survey of salaries during february 2020. 
Calculating media and mean of net salaries (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ )


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# importing pandas, reading CSV file and storing in pandas Data Frame, then storing in numpy array to play
import pandas as pd 
pd_salary = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Notebooks/1.DSBZ/3.DataFrames/OpenQube2020.csv')
np_salary = np.array(pd_salary)


In [ ]:
pd_salary["Salario mensual NETO (en tu moneda local)"].median()

60000.0

In [ ]:
### Calc mean only from  "Salario NETO" column
pd_salary["Salario mensual NETO (en tu moneda local)"].mean()

12619504102.123568