<a href="https://colab.research.google.com/github/pedrociancaglini-ey/EY-Badges/blob/main/DSBZ_numpy_ciancaglini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Excercise 1:  
#### Create an array of 100 random elements. Calc median. 

Author: Pedro Ciancaglini

In [1]:
# Importing required libraries
import numpy as np

In [5]:
# Creating our random array with 100 elements
random_array = np.random.randint(100,size=100)
random_array

array([51, 98, 38, 39, 46, 26, 95, 96,  2, 72, 26, 49,  8, 21, 99, 67, 87,
       11, 76, 84, 86, 91, 92,  9, 56, 79, 24, 85,  8, 27, 75, 90, 25, 34,
       75, 61, 65, 61, 52, 41, 34,  3, 88,  3, 87, 16, 40, 57, 59, 29,  3,
        7, 80, 24, 91, 58, 36, 76, 76, 23, 14, 79, 93, 75, 48, 12, 63, 71,
       58, 99, 12, 98, 60, 42, 82, 18, 95, 72, 21, 85, 37, 16, 22,  2, 55,
       36, 66, 37,  2, 12, 30, 93, 20,  5, 73, 57, 30, 37, 51, 70])

In [3]:
# Calculating median
median_array = np.median(random_array)
median_array

58.0

In [7]:
# With reshape, you can create a Matrix from an Array 
reshaped_array = random_array.reshape(10,10) # 10x10 Matrix
print(reshaped_array)

[[51 98 38 39 46 26 95 96  2 72]
 [26 49  8 21 99 67 87 11 76 84]
 [86 91 92  9 56 79 24 85  8 27]
 [75 90 25 34 75 61 65 61 52 41]
 [34  3 88  3 87 16 40 57 59 29]
 [ 3  7 80 24 91 58 36 76 76 23]
 [14 79 93 75 48 12 63 71 58 99]
 [12 98 60 42 82 18 95 72 21 85]
 [37 16 22  2 55 36 66 37  2 12]
 [30 93 20  5 73 57 30 37 51 70]]


In [ ]:
##### funcion para seleccionar un elemento del Array Aleatorio ######
def seleccion(arr):
   
    eleccion = int(input("Seleccionar un vector del Array para operar> ")) # Pedimos seleccionar un vector del array

    while eleccion > len(arr):                                             # Volvemos a pedirlo si no es valido
        eleccion = int(input("Debe ser un vector del array> "))
    
    return arr[eleccion,]                                                  # Retornamos vector seleccionado del array

print(seleccion(Array_reshaped))                                           # Probamos la funcion, imprimiendo el vector

Seleccionar un vector del Array para operar> 1
[85 75  0 56 73 72 88 35 65 80]


## Ejercicio 2> 
#### Recordar los ejercicios con funciones para cálculo de factorial y suma de serie. Repetir ambos ejercicios (puede ser sobre el mismo código), pero ahora utilizar las nuevas operaciones aprendidas con los ndarrays.

###### Probamos primero con la adición en serie

In [ ]:
def adicion(arr):                                            # Definimos funcion para sumar elementos del vector en serie
    suma = 0                                                 # inicializamos la variable Suma en 0
    
    for i in arr:                                            # Realizamos la adicion por medio de un loop
        suma += i

    print("Resultado por Loop: ",suma)                       # imprimimos el resultado del loop
    print("Resultado por func sum()'' Numpy: ", arr.sum())   # funcion de Numpy realiza suma de los elementos del vector

In [ ]:
adicion(seleccion(Array_reshaped))  # invocamos a la funcion adicion, indicando previamente el vector del array

Seleccionar un vector del Array para operar> 1
Resultado por Loop:  402
Resultado por func sum()'' Numpy:  402


In [ ]:
%time 
arr = np.random.randint(1000, size=(100,100))


adicion(arr)

CPU times: user 10 µs, sys: 2 µs, total: 12 µs
Wall time: 19.8 µs
Resultado por Loop:  [48399 51871 50160 45173 53618 50139 45245 48830 47092 49642 51354 50554
 50116 52910 51623 50303 50422 53381 57708 50001 49157 53036 51121 49848
 50303 46014 52239 45245 47564 49295 51335 49650 48139 51973 49587 47043
 47434 51742 52452 50577 52996 48539 48655 51132 48651 52727 49463 50298
 53852 51939 49756 53903 49602 48656 49139 51648 52121 51463 49148 48892
 46490 53905 48650 53869 51307 48723 50094 49272 52145 49110 52269 50934
 53633 51677 50886 48769 44690 49462 48043 54261 50891 51226 51220 53120
 50645 48727 48789 49588 47911 52812 47182 49148 49588 50516 50988 45993
 51505 48259 54034 53849]
Resultado por func sum()'' Numpy:  5029055


In [ ]:
%time

arr.sum()

CPU times: user 8 µs, sys: 0 ns, total: 8 µs
Wall time: 15 µs


5029055

### Nota:

__Una gran feature de jupyter son las magic functions, en este caso utilice la de `%time` nos permite mirar rapido cuanto tarda en correr nuestra celda__

__Esta super interesante que observes que cuando el vector es chico, los tiempos son similares entre realizar un loop y el metodo de NumPy pero a medida que el vector crece el for loop va quedando lento al lado de aprovechar la velocidad de numpy para realizar estos calculos.__

###### Operaciones con dos vectores del array (Suma y Producto)

In [ ]:
def sum_vectores(vec1,vec2):                # Definimos funcion en donde sumamos 2 vectores del array
    resultado = vec1 + vec2                 # Guardamos el resultado de la suma de los dos vectores en variable "resultado"
    return resultado                        # Retornamos resultado

In [ ]:
print(sum_vectores(seleccion(Array_reshaped),seleccion(Array_reshaped)))  # imprimimos la suma de dos vectores

Seleccionar un vector del Array para operar> 1
Seleccionar un vector del Array para operar> 2
[131 169  75 105 172 109 128  89 140 107]


In [ ]:
a = np.random.randint(10, size=(3,4))

b = np.random.randint(10, size=(2,10))
sum_vectores(a,b)

ValueError: operands could not be broadcast together with shapes (3,4) (2,10) 

### Detalle:

__Un detalle nada mas, que estaria bueno que la funcion haga un check si ambos vectores que entran a la suma o multiplicacion son compatibles para realizar la operacion__

In [ ]:
def prod_vectores(vec1, vec2):             # Definimos funcion en donde hacemos el producto vectorial de 2 vectores del array
    resultado = np.matmul(vec1, vec2)      # Guardamos el resultado del producto de los dos vectores en variable "resultado"
    return resultado                       # Retornamos resultado

In [ ]:
prod_vectores(seleccion(Array_reshaped),seleccion(Array_reshaped))  # imprimimos el producto de dos vectores

Seleccionar un vector del Array para operar> 1
Seleccionar un vector del Array para operar> 2


36040

## Ejercicio 3> 
#### En este link se provee un archivo con los resultados de la Encuesta de Sueldos de Openqube de Febrero 2020 (https://sueldos.openqube.io/encuesta-sueldos-2020.02/ ), Calcular y comparar media y mediana de los sueldos netos.


In [ ]:
### Calculando mean y median utilizando (1) Pandas y (2) Numpy.
import pandas as pd                               # importamos pandas
salarios_pd = pd.read_excel('Salarios_OQ.xlsx')   # importamos dataset "Salarios_OQ.xlsx" a pandas dataframe
salarios_np = np.array(salarios_pd)               # importamos dataset      "             a numpy array


FileNotFoundError: [Errno 2] No such file or directory: 'Salarios_OQ.xlsx'

#### Calculo con Numpy

In [ ]:
salario_neto = salarios_np[:,30]                  # Creando un vector unico con toda la data de salario neto

In [ ]:
np.median(salario_neto)                           # Calculando la mediana de la columna "Salario Neto"

76000.0

In [ ]:
np.mean(salario_neto)                             # Calculando el mean de la columna "Salario Neto"

nan

In [ ]:
Salarios_Netos_Limpios = salario_neto[salario_neto >= 0]   # Separamos aquellos registros que son numericos

<ipython-input-17-0cf23a1c94e6>:1: RuntimeWarning: invalid value encountered in greater_equal
  Salarios_Netos_Limpios = salario_neto[salario_neto >= 0]   # Separamos aquellos registros que son numericos


In [ ]:
np.mean(Salarios_Netos_Limpios)                            # Calculo mean con numpy, con array solo numerico

19309452.112037756

#### Calculando con Pandas

In [ ]:
### Calculando la mediana solo de la columna "Salario NETO" segun lo solicitado en el ejercicio
salarios_pd["Salario mensual NETO (en tu moneda local)"].median()

76000.0

In [ ]:
### Calculando el mean solo de la columna "Salario NETO" segun lo solicitado en el ejercicio
salarios_pd["Salario mensual NETO (en tu moneda local)"].mean()

19309452.112037756

### Un ultimo detalle:

__A diferencia quizas de otro lenguajes, en  python las mejores practicas indican que al nombrar variables se evite el uso de mayusculas. Por ejemplo una variable que definiste se llama `Array_aleatorio` lo mejor seria que utilicemos todas minusculas con `_` que separen las palabras: `array_aleatorio`.__

__Por si te interesa Pedro, ya que noto que sos una persona curiosa, te dejo un [link](https://pep8.org/#names-to-avoid) donde cuentan las PEP8 que son las mejores practicas de escritura de codigo para python. No es necesario que las uses simplemente te paso el dato por si queres chusmear.__